library(epidata)

if (at_home()) {
  suppressMessages(expect_true(inherits(get_annual_wages_and_work_hours(), "data.frame")))
  # expect_true(inherits(get_annual_wages_by_wage_group(), "data.frame"))
  # expect_true(inherits(get_black_white_wage_gap(), "data.frame"))
  # expect_true(inherits(get_college_wage_premium(), "data.frame"))
  # expect_true(inherits(get_compensation_wages_and_benefits(), "data.frame"))
  # expect_true(inherits(get_employment_to_population_ratio(), "data.frame"))
  # expect_true(inherits(get_gender_wage_gap(), "data.frame"))
  # expect_true(inherits(get_health_insurance_coverage(), "data.frame"))
  # expect_true(inherits(get_hispanic_white_wage_gap(), "data.frame"))
  # expect_true(inherits(get_labor_force_participation_rate(), "data.frame"))
  # expect_true(inherits(get_long_term_unemployment(), "data.frame"))
  # expect_true(inherits(get_median_and_mean_wages(), "data.frame"))
  # expect_true(inherits(get_minimum_wage(), "data.frame"))
  # expect_true(inherits(get_non_high_school_wage_penalty(), "data.frame"))
  # expect_true(inherits(get_pension_coverage(), "data.frame"))
  # expect_true(inherits(get_poverty_level_wages(), "data.frame"))
  # expect_true(inherits(get_productivity_and_hourly_compensation(), "data.frame"))
  # expect_true(inherits(get_underemployment(), "data.frame"))
  # expect_true(inherits(get_unemployment(), "data.frame"))
  # expect_true(inherits(get_unemployment_by_state(), "data.frame"))
  # expect_true(inherits(get_union_coverage(), "data.frame"))
  # expect_true(inherits(get_wages_by_education(), "data.frame"))
  # expect_true(inherits(get_wages_by_percentile(), "data.frame"))
  # expect_true(inherits(get_wage_decomposition(), "data.frame"))
  # expect_true(inherits(get_wage_ratios(), "data.frame"))
} else {
  expect_false(not_dos())
}